steps:
  # Bước 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sanlexai-repo/hello-agent:$SHORT_SHA'
      - '.'

  # Bước 2: Chạy Unit Tests (Cải tiến)
  # Chạy container từ image vừa build và thực thi lệnh pytest bên trong nó.
  - name: 'gcr.io/cloud-builders/docker'
    id: Test
    entrypoint: 'sh'
    args:
    - '-c'
    - |
      docker run \
        us-central1-docker.pkg.dev/$PROJECT_ID/sanlexai-repo/hello-agent:$SHORT_SHA \
        pytest
    wait_for: [Build]

  # Bước 3: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sanlexai-repo/hello-agent:$SHORT_SHA'
    wait_for: [Test]

  # Bước 4: Triển khai lên Cloud Run
  - name: 'gcr.io/google-cloud-sdk/gcloud'
    id: Deploy
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'hello-agent-service'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/sanlexai-repo/hello-agent:$SHORT_SHA'
      - '--region=asia-southeast1'
      - '--platform=managed'
      - '--quiet'
    wait_for: [Push]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/sanlexai-repo/hello-agent:$SHORT_SHA'